---
# tasks file for lighthouse-role
    - name: Remove existing lighthouse directory if exists
      ansible.builtin.file:
        path: "{{ lighthouse_dir }}"
        state: absent

    - name: Create lighthouse directory
      ansible.builtin.file:
        path: "{{ lighthouse_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Clone Lighthouse repository
      ansible.builtin.git:
        repo: "https://github.com/VKCOM/lighthouse.git"
        dest: "{{ lighthouse_dir }}"
        version: master
        force: true

    - name: Set correct permissions for lighthouse
      ansible.builtin.file:
        path: "{{ lighthouse_dir }}"
        owner: www-data
        group: www-data
        recurse: true
        state: directory
